# Reads SPV_FILE and writes HEADER_FILE containing its bytes as a
# `static const uint32_t <SYMBOL_NAME>[]` array plus a `<SYMBOL_NAME>_size` byte count.
# Invoked as a CMake script (cmake -P) from kernels/CMakeLists.txt's mirage_embed_spirv().

file(READ "${SPV_FILE}" SPV_HEX HEX)
string(LENGTH "${SPV_HEX}" SPV_HEX_LEN)
math(EXPR SPV_BYTE_COUNT "${SPV_HEX_LEN} / 2")

string(REGEX MATCHALL "[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]" SPV_WORDS "${SPV_HEX}")

set(SPV_ARRAY_BODY "")
foreach(WORD ${SPV_WORDS})
    # SPIR-V words are little-endian; HEX reads bytes in file order, so reverse
    # each 4-byte group back into a little-endian uint32_t literal.
    string(SUBSTRING "${WORD}" 0 2 B0)
    string(SUBSTRING "${WORD}" 2 2 B1)
    string(SUBSTRING "${WORD}" 4 2 B2)
    string(SUBSTRING "${WORD}" 6 2 B3)
    string(APPEND SPV_ARRAY_BODY "0x${B3}${B2}${B1}${B0},")
endforeach()

file(WRITE "${HEADER_FILE}" "// Auto-generated by kernels/EmbedSpirv.cmake from ${SPV_FILE}. Do not edit.\n#pragma once\n#include <cstdint>\n#include <cstddef>\nstatic const uint32_t ${SYMBOL_NAME}[] = {${SPV_ARRAY_BODY}};\nstatic const size_t ${SYMBOL_NAME}_size = ${SPV_BYTE_COUNT};\n")
